# Travis CI configuration to run automated test when pushing to github
language: node_js
node_js:
 - "10"

install:
  - node --version
  - npm i -g npm@5
  - npm --version
  - npm install

script:
  - npm run test:ci
  # TODO: could also run lit 